services:
  - type: web
    name: invoice-generator-backend
    env: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && pnpm dlx puppeteer browsers install chrome
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
